config/routes.rb
Rails.application.routes.draw do
  devise_for :staffs
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord
    has_many :appointments
    has_many :staffs, through: :appointments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
    belongs_to :animal
    belongs_to :staff
end

app/models/staff.rb
class Staff < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attribute :tos_agreement, :boolean
  validates_acceptance_of :tos_agreement, allow_nil: false, accept: true, on: :create

  has_many :appointments
  has_many :animals, through: :appointments

  PROFESSION = {
    vet: 'veterinarian',
    assistant: 'veterinary assistant',
    carer: 'carer',
    groomer: 'groomer',
    technician: 'veterinary technician'
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :age, :vet, :profession, :tos_agreement])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Home page</h1>

<% if staff_signed_in? %>
    <%= link_to('Logout', destroy_staff_session_path, method: :delete) %>
<% else %>
    <%= link_to('Login', new_staff_session_path) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vets4pets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>